#!/usr/bin/env python3
"""
join-sources.py — put the wallet and the app class back together from their parts.

    python3 tools/join-sources.py          # write Web/foxy-wallet.js and build/foxy-app.js
    python3 tools/join-sources.py --check  # fail if either differs from its parts

The wallet (build/wallet/*.js) and the app class (build/app/*.js) are kept in
parts by feature, for reading and review. They are pieces of one file each,
joined in name order with a GENERATED line on top; nothing is transformed.
pack-index.py runs this first. check-all.sh runs --check first, so an edit made
to a generated file instead of its parts is caught rather than overwritten.
"""
import glob, os, re, sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
TARGETS = [
    ('build/wallet', 'Web/foxy-wallet.js'),
    ('build/app', 'build/foxy-app.js'),
]


def joined(folder):
    parts = sorted(glob.glob(os.path.join(ROOT, folder, '*.js')))
    if not parts:
        sys.exit('no parts in ' + folder)
    text = ''
    for p in parts:
        chunk = open(p, encoding='utf-8', newline='').read()
        text += chunk if chunk.endswith('\n') else chunk + '\n'
    header = ('// GENERATED by tools/join-sources.py from %s/*.js \u2014 edit those, '
              'then run python3 tools/pack-index.py\n' % folder)
    return header + text


INTRO = {
    'build/wallet': ('build/wallet \u2014 the wallet, by part', 'The wallet (all money logic)', 'Web/foxy-wallet.js'),
    'build/app': ('build/app \u2014 the app class, by part', "The app component (every screen's behaviour)", 'build/foxy-app.js'),
}


def readme(folder, target):
    """A table of the parts and what each defines, read from the code itself."""
    title, what, _ = INTRO[folder]
    rows = []
    for p in sorted(glob.glob(os.path.join(ROOT, folder, '*.js'))):
        text = open(p, encoding='utf-8', newline='').read()
        if folder == 'build/wallet':
            names = re.findall(r'^  function ([A-Za-z_$][\w$]*)|^    ([A-Za-z_$][\w$]*): function', text, re.M)
            names = [a or b for a, b in names]
        else:
            names = re.findall(r'^  (?:async )?([A-Za-z_$][\w$]*)\([^)]*\) \{$', text, re.M)
            names = [n for n in names if n not in ('if', 'for', 'while', 'switch', 'catch')]
        # Every name, not the first fourteen. These two READMEs are the only
        # index the repository generates, and the cap hid 212 of its own
        # function names — setProofs, addProofs, exportProofs, claimUnclaimed
        # and _requestPaid among them, which are the ones AUDIT.md sends a
        # reviewer to read.
        shown = ', '.join('`%s`' % n for n in names)
        rows.append('| `%s` | %d | %s |' % (os.path.basename(p), text.count('\n'), shown or '\u2014'))
    return '\n'.join([
        '# ' + title, '',
        '%s is kept here in parts by feature, so it can be read a part at a time. '
        '`tools/join-sources.py` joins these files, in name order, into `%s` \u2014 the file that is '
        'used \u2014 and `sh tools/check-all.sh` fails if the two ever differ. **Edit these files, never '
        '`%s`,** then run `python3 tools/pack-index.py`.' % (what, target, target), '',
        'The parts are pieces of one file, not separate modules: they share one scope, so a part '
        'is not valid JavaScript on its own. This table is regenerated on every join.', '',
        '| Part | Lines | Defines |', '|---|---|---|'] + rows + [''])


def main():
    check = '--check' in sys.argv
    stale = []
    for folder, target in TARGETS:
        want = joined(folder)
        path = os.path.join(ROOT, target)
        have = open(path, encoding='utf-8', newline='').read() if os.path.exists(path) else None
        # the part README is generated too, so --check compares it as well
        table = readme(folder, target)
        rp = os.path.join(ROOT, folder, 'README.md')
        have_table = open(rp, encoding='utf-8').read() if os.path.exists(rp) else None
        if check:
            if have != want:
                stale.append(target)
            if have_table != table:
                stale.append(folder + '/README.md')
        else:
            if have != want:
                open(path, 'w', encoding='utf-8', newline='').write(want)
                print('wrote %s from %s' % (target, folder))
            if have_table != table:
                open(rp, 'w', encoding='utf-8').write(table)
    if check:
        if stale:
            print('out of date with their parts: ' + ', '.join(stale))
            print('edit the parts (build/wallet, build/app), not the joined files, then run python3 tools/join-sources.py')
            sys.exit(1)
        print('joined sources match their parts')


if __name__ == '__main__':
    main()
