#!/bin/sh
# verify-shipped.sh — the shipped page and wallet are exactly what the sources make.
#
#     sh tools/verify-shipped.sh           # check the commit HEAD names
#     sh tools/verify-shipped.sh <commit>  # check another commit
#
# Three files that ship are generated, and a reviewer reads their sources, not
# them:
#
#     Web/foxy-wallet.js   joined from build/wallet/*.js   (tools/join-sources.py)
#     build/foxy-app.js    joined from build/app/*.js      (tools/join-sources.py)
#     Web/index.html       packed from build/foxy-app.js, build/markup.html,
#                          build/foxy-render.js and build/shell (tools/pack-index.py)
#
# This takes a clean export of the commit (git archive, so nothing uncommitted
# and nothing gitignored is involved), deletes the three generated files from a
# build copy, regenerates them with the repo's own scripts, and compares each
# byte for byte with the committed file. It prints the SHA-256 of every file
# that ships from Web/, so the output can be compared with what is in an app
# bundle.
#
# THE SHELL IS A SOURCE TOO
#
# The shell is everything in the page that is not the app class or the markup:
# the loader script, the page policy, the tail, and the manifest of embedded
# fonts, images, React, ReactDOM and the renderer. It is
# committed under build/shell, and the page is regenerated from the export
# alone; before, it was unpacked from the committed Web/index.html, so the check
# could not see a change made to the shell inside the page. The pins below stay
# as a second line: the manifest must hold exactly the nine entries listed, each
# with the hash given (the renderer: the hash of build/foxy-render.js), and the
# page may hold exactly one inline script, the pinned loader, under the pinned
# page policy.
#
# Needs git, python3 and shasum. No network. Writes only to a mktemp directory.
# Exits 0 only if every file matches.
set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)
REV=${1:-HEAD}
WORK=$(mktemp -d "${TMPDIR:-/tmp}/verify-shipped.XXXXXX")
trap 'rm -rf "$WORK"' EXIT

commit=$(git -C "$ROOT" rev-parse --verify "$REV^{commit}")
echo "commit $commit"

# 1. two clean exports: one is the reference, the other is rebuilt
git -C "$ROOT" archive --format=tar -o "$WORK/src.tar" "$commit"
mkdir "$WORK/ref" "$WORK/build"
tar -xf "$WORK/src.tar" -C "$WORK/ref"
tar -xf "$WORK/src.tar" -C "$WORK/build"

# 2. nothing is taken from the committed page: the shell's sources are in the export

# 3. remove the generated files, so a regeneration that silently did nothing
#    cannot pass by leaving the committed copy in place
rm -f "$WORK/build/Web/foxy-wallet.js" "$WORK/build/build/foxy-app.js" "$WORK/build/Web/index.html"

# 4. regenerate with the repo's own build step (it runs join-sources.py first)
( cd "$WORK/build" && python3 tools/pack-index.py >/dev/null )

# 5. compare
fail=0
for f in Web/foxy-wallet.js build/foxy-app.js Web/index.html; do
  if [ ! -f "$WORK/build/$f" ]; then
    printf '  FAIL  %-20s not regenerated\n' "$f"; fail=$((fail + 1)); continue
  fi
  if cmp -s "$WORK/build/$f" "$WORK/ref/$f"; then
    printf '  ok    %-20s regenerated byte for byte  %s\n' "$f" "$(shasum -a 256 "$WORK/ref/$f" | cut -d' ' -f1)"
  else
    printf '  FAIL  %-20s differs from its sources\n' "$f"
    printf '          committed    %s\n' "$(shasum -a 256 "$WORK/ref/$f" | cut -d' ' -f1)"
    printf '          regenerated  %s\n' "$(shasum -a 256 "$WORK/build/$f" | cut -d' ' -f1)"
    fail=$((fail + 1))
  fi
done

# 6. what the shell carries, checked against a fixed list
python3 - "$WORK/ref" <<'PY' || fail=$((fail + 1))
import base64, gzip, hashlib, json, os, re, sys
ref = sys.argv[1]
h = open(os.path.join(ref, 'Web/index.html'), encoding='utf-8', newline='').read()
render = hashlib.sha256(open(os.path.join(ref, 'build/foxy-render.js'), 'rb').read()).hexdigest()
WANT = {
    '64b433ba-e6ef-4c0b-9d49-9dacd943871b': ('text/javascript', render, 'renderer = build/foxy-render.js'),
    '8d4aa6b2-16cb-4c42-a6f2-d85feb8c0047': ('text/javascript', 'd949f1c3687aedadcedac85261865f29b17cd273997e7f6b2bfc53b2f9d4c4dd', 'react 18.3.1'),
    '93c76fbd-259d-463c-a60d-5ed97ad7e690': ('text/javascript', '35f4f974f4b2bcd44da73963347f8952e341f83909e4498227d4e26b98f66f0d', 'react-dom 18.3.1'),
    '21177c5f-9104-4fe5-a9b5-e02de44163b0': ('image/svg+xml', '9c84c033a7279c6688c675d114c600873d8c59936674b0e3813e77b87fdd9fde', 'icon (bolt)'),
    '0e7a9336-3355-4315-871d-237a54736709': ('image/svg+xml', '6c38e984fed9b05103a0319727fbdb39584d78d7f92456ee9fc2af07c84b4d98', 'icon'),
    'ef48d7d8-7097-417b-bcd9-31588805be02': ('font/woff2', 'f153aa07c1b16fbb12391c2512860c97819a0a9fd014f338b2b3f12496479d13', 'font'),
    'ccd2d25b-da8b-4c54-afc7-0396a1360306': ('font/woff2', '8330490a01c60c196eae00b823de8102275aaa5862e7b76a7af21b8745338928', 'font'),
    'ad30d34a-2e66-4858-bc76-fce22b7ce8e5': ('font/woff2', 'df4fca18912e29202b16286ab514798de8357c416b5e1f2dd31703994bec7a78', 'font'),
    '94600041-dd05-498a-9e76-89cefb385282': ('font/woff2', 'd2909123a6a8ed2f928055f002c32f63ee93496b470c1a344873f955111fca53', 'font'),
}
tag = '<script type="__bundler/manifest">'
a = h.index(tag) + len(tag)
man = json.loads(h[a:h.index('</script>', a)].strip())
bad = 0
for k in sorted(set(man) | set(WANT)):
    if k not in WANT:
        print('  FAIL  manifest entry %s (%s) is not on the list' % (k[:8], man[k].get('mime'))); bad += 1; continue
    if k not in man:
        print('  FAIL  manifest entry %s (%s) is missing' % (k[:8], WANT[k][2])); bad += 1; continue
    raw = base64.b64decode(man[k].get('data', ''))
    if man[k].get('compressed'):
        raw = gzip.decompress(raw)
    got = hashlib.sha256(raw).hexdigest()
    mime, digest, label = WANT[k]
    if got != digest or man[k].get('mime') != mime:
        print('  FAIL  manifest %s %s: %s %s' % (k[:8], label, man[k].get('mime'), got)); bad += 1
print('  %s  manifest: %d entries, each the expected type and hash' % ('ok  ' if not bad else 'FAIL', len(man)))
# the page's own scripts: every <script> in the shell is one of the bundler's
# data blocks, or the one inline loader
template_tag = '<script type="__bundler/template">'
t = h.index(template_tag) + len(template_tag)
shell = h[:t] + h[h.index('</script>', t):]
inline = re.findall(r'<script>(.*?)</script>', shell, re.S)
# the loader's own text builds script tags for blob URLs as strings, so tags are
# counted in the shell with the loader's body taken out
outside = re.sub(r'<script>.*?</script>', '<script></script>', shell, flags=re.S)
tags = re.findall(r'<script(?: [^>]*)?>', outside)
other = [s for s in tags if s != '<script>' and 'type="__bundler/' not in s]
# What the shell may be is also pinned here: the loader's hash, the exact page
# policy, and the bundler's four data blocks. build/shell is reviewed as source;
# these make a change to the loader, a looser script-src or an extra block fail
# loudly as well. A deliberate change updates these three.
LOADER_SHA256 = '5fb1a16fc0d880462561dc02d66ca46d50ceee2f1297f5d2e126fe1b3754cb52'
POLICY = ("default-src 'self' file: blob: data:; script-src 'self' file: blob: "
          "'sha256-X7Ghb8DYgEYlYdwC1mykbVDO7i8Sl/XS4Sb+GzdUy1I='; style-src 'self' file: blob: "
          "'unsafe-inline'; img-src 'self' file: blob: data:; font-src 'self' file: blob: data:; "
          "connect-src 'self' file: blob: data:; object-src 'none'; base-uri 'none'; frame-src 'none'; "
          "form-action 'none'")
BLOCKS = ['__bundler/ext_resources', '__bundler/manifest', '__bundler/page_order', '__bundler/template']
if len(inline) != 1 or other:
    print('  FAIL  shell scripts: %d inline, others %s' % (len(inline), other)); bad += 1
else:
    loader = inline[0].replace('\r\n', '\n').replace('\r', '\n')
    got = hashlib.sha256(loader.encode('utf-8')).hexdigest()
    if got != LOADER_SHA256:
        print('  FAIL  shell: the loader is not the pinned one (sha256 %s)' % got); bad += 1
    else:
        print('  ok    shell: one inline script, the pinned loader (sha256 %s…, %d bytes)'
              % (got[:8], len(loader.encode('utf-8'))))
policy = re.search(r'<meta http-equiv="Content-Security-Policy" content="([^"]*)">', shell)
if not policy or policy.group(1) != POLICY:
    print('  FAIL  page policy is not the pinned one: %s' % (policy.group(1) if policy else '<none>')); bad += 1
else:
    print('  ok    page policy: exactly the pinned one')
blocks = sorted(set(re.findall(r'<script type="(__bundler/[a-z_]+)"', h)))
EXT_RESOURCES_SHA256 = 'f225e7249f896abc750b587739c0754b545f5bdd960c57e3b6d5ad0f30718277'
def block(name):
    tg = '<script type="__bundler/%s">' % name
    a = h.index(tg) + len(tg)
    return h[a:h.index('</script>', a)].strip()
if blocks != BLOCKS:
    print('  FAIL  bundler blocks %s, expected %s' % (blocks, BLOCKS)); bad += 1
elif hashlib.sha256(block('ext_resources').encode('utf-8')).hexdigest() != EXT_RESOURCES_SHA256:
    print('  FAIL  ext_resources is not the pinned one: %s' % block('ext_resources')[:120]); bad += 1
elif block('page_order') != '[]':
    print('  FAIL  page_order is not empty: %s' % block('page_order')[:120]); bad += 1
else:
    print('  ok    bundler blocks: the four expected, ext_resources and page_order as pinned')
sys.exit(1 if bad else 0)
PY

# 7. every file Web/ ships, for comparison with an app bundle
echo
echo "files in Web/ at $commit:"
( cd "$WORK/ref/Web" && find . -type f ! -name '*.md' | LC_ALL=C sort | sed 's|^\./||' | xargs shasum -a 256 | sed 's/^/  /' )

echo
if [ "$fail" = 0 ]; then
  echo "VERIFIED: Web/foxy-wallet.js, build/foxy-app.js and Web/index.html are what their sources at ${commit%"${commit#????????????}"} make"
else
  echo "$fail problem(s)"
fi
[ "$fail" = 0 ]
