var FoxyBip39=(()=>{var W=Object.defineProperty;var Xe=Object.getOwnPropertyDescriptor;var Pe=Object.getOwnPropertyNames;var Je=Object.prototype.hasOwnProperty;var Ye=(e,t,r)=>t in e?W(e,t,{enumerable:!0,configurable:!0,writable:!0,value:r}):e[t]=r;var Qe=(e,t)=>{for(var r in t)W(e,r,{get:t[r],enumerable:!0})},Ze=(e,t,r,o)=>{if(t&&typeof t=="object"||typeof t=="function")for(let n of Pe(t))!Je.call(e,n)&&n!==r&&W(e,n,{get:()=>t[n],enumerable:!(o=Xe(t,n))||o.enumerable});return e};var Ve=e=>Ze(W({},"__esModule",{value:!0}),e);var l=(e,t,r)=>Ye(e,typeof t!="symbol"?t+"":t,r);var mt={};Qe(mt,{generateMnemonic:()=>De,mnemonicToSeed:()=>We,mnemonicToSeedSync:()=>Re,validateMnemonic:()=>Me,wordlist:()=>Ne});function fe(e){return e instanceof Uint8Array||ArrayBuffer.isView(e)&&e.constructor.name==="Uint8Array"&&"BYTES_PER_ELEMENT"in e&&e.BYTES_PER_ELEMENT===1}var Z=e=>e?`"${e}" `:"";function w(e,t=""){if(typeof e!="number")throw new TypeError(Z(t)+"expected number, got "+typeof e);if(!Number.isSafeInteger(e)||e<0)throw new RangeError(Z(t)+"expected integer >= 0, got "+e);return e}function T(e,t,r=""){if(fe(e)&&(t===void 0||e.length===t))return e;t!==void 0&&w(t,"length");let o=fe(e),n=t!==void 0?` of length ${t}`:"",a=o?`length=${e.length}`:`type=${typeof e}`,i=Z(r)+"expected Uint8Array"+n+", got "+a;throw o?new RangeError(i):new TypeError(i)}function R(e){if(typeof e!="function"||typeof e.create!="function")throw new TypeError("expected hash wrapped by utils.createHasher");if(w(e.outputLen),w(e.blockLen),e.outputLen<1||e.blockLen<1)throw new Error("hash blockLen / outputLen must be >= 1")}var et=(e,t)=>{if(e===null||typeof e!="object"||Array.isArray(e))throw new TypeError((t==="object"?"":`"${t}" `)+"expected object, got type="+typeof e)},he=(e,t)=>{et(e,t);let r=Object.getPrototypeOf(e);if(r!==Object.prototype&&r!==null)throw new TypeError(`"${t}" expected plain object`);if(Object.hasOwn(e,"__proto__"))throw new TypeError(`"${t}.__proto__" is not allowed`)};function I(e,t=!0){if(e.destroyed)throw new Error("hash was destroyed");if(t&&e.finished)throw new Error("digest() was already called")}function N(e,t){T(e,void 0,"output");let r=t.outputLen;if(!(e.length>=r))throw new RangeError('"output" expected length >= '+r)}function y(...e){for(let t=0;t<e.length;t++)e[t].fill(0)}function C(e){return new DataView(e.buffer,e.byteOffset,e.byteLength)}function k(e,t){return e<<32-t|e>>>t}function tt(e){let t=globalThis;if(typeof t.scheduler?.yield=="function"){let r=t.scheduler.yield();return e&&r.catch(e),r}return new Promise(r=>t.setTimeout(r,0))}async function pe(e,t,r,o){if(w(e,"iters"),w(t,"tick"),typeof r!="function")throw new TypeError("callback must be a function");let n=Date.now();for(let a=0;a<e;a++){r(a);let i=Date.now()-n;i>=0&&i<t||(await tt(o),n=Date.now())}}function rt(e){if(typeof e!="string")throw new TypeError("string expected");let t=new TextEncoder().encode(e);try{return new Uint8Array(t)}finally{y(t)}}function V(e,t=""){return typeof e=="string"?rt(e):T(e,void 0,t)}function ee(e,t,r="opts"){return he(e,"defaults"),t!==void 0&&he(t,r),Object.assign(Object.create(null),e,t)}function te(e,t={}){if(typeof e!="function")throw new TypeError('"hashCons" expected function, got type='+typeof e);t=ee({},t,"info");let r=(n,a)=>e(a).update(n).digest(),o=e(void 0);return r.outputLen=o.outputLen,r.blockLen=o.blockLen,r.canXOF=o.canXOF,r.create=n=>e(n),Object.assign(r,t),Object.freeze(r)}function be(e=32){w(e,"bytesLength");let t=typeof globalThis=="object"?globalThis.crypto:null;if(typeof t?.getRandomValues!="function")throw new Error("crypto.getRandomValues must be defined");if(e>65536)throw new RangeError(`"bytesLength" expected <= 65536, got ${e}`);return t.getRandomValues(new Uint8Array(e))}var re=e=>({oid:Uint8Array.from([6,9,96,134,72,1,101,3,4,2,e])});var K=class{constructor(t,r){l(this,"oHash");l(this,"iHash");l(this,"blockLen");l(this,"outputLen");l(this,"canXOF",!1);l(this,"finished",!1);l(this,"destroyed",!1);if(R(t),T(r,void 0,"key"),this.iHash=t.create(),typeof this.iHash.update!="function")throw new Error("expected Hash instance");this.blockLen=this.iHash.blockLen,this.outputLen=this.iHash.outputLen;let o=this.blockLen,n=new Uint8Array(o);n.set(r.length>o?t.create().update(r).digest():r);for(let a=0;a<n.length;a++)n[a]^=54;this.iHash.update(n),this.oHash=t.create();for(let a=0;a<n.length;a++)n[a]^=106;this.oHash.update(n),y(n)}update(t){return I(this),this.iHash.update(t),this}digestInto(t){I(this),N(t,this),this.finished=!0;let r=t.subarray(0,this.outputLen);this.iHash.digestInto(r),this.oHash.update(r),this.oHash.digestInto(r),this.destroy()}digest(){let t=new Uint8Array(this.oHash.outputLen);return this.digestInto(t),t}_cloneInto(t){t||(t=Object.create(Object.getPrototypeOf(this),{}));let{oHash:r,iHash:o,finished:n,destroyed:a,blockLen:i,outputLen:s,canXOF:c}=this;return t=t,t.finished=n,t.destroyed=a,t.blockLen=i,t.outputLen=s,t.canXOF=c,t.oHash=r._cloneInto(t.oHash),t.iHash=o._cloneInto(t.iHash),t}clone(){return this._cloneInto()}destroy(){this.destroyed=!0,this.oHash.destroy(),this.iHash.destroy()}},me=(()=>{let e=(t,r,o)=>new K(t,r).update(o).digest();return e.create=(t,r)=>new K(t,r),e})();function ge(e,t,r,o){R(e);let n=ee({dkLen:32,asyncTick:10},o),{c:a,dkLen:i,asyncTick:s}=n;if(w(a,"c"),w(i,"dkLen"),w(s,"asyncTick"),a<1)throw new Error('"c" (iterations) must be >= 1');if(i<1)throw new Error('"dkLen" must be >= 1');if(i>(2**32-1)*e.outputLen)throw new Error("derived key too long");let c=V(t,"password");try{let d=V(r,"salt");try{let f=new Uint8Array(i),{iHash:h,oHash:u,outputLen:p}=me.create(e,c),m=new Uint8Array(p),g=ot(h,u,d,m);return{c:a,dkLen:i,asyncTick:s,DK:f,outputLen:p,eng:g}}finally{typeof r=="string"&&y(d)}}finally{typeof t=="string"&&y(c)}}function ot(e,t,r,o){let n=new Uint8Array(4),a=C(n),i=e._cloneInto().update(r),s=t._cloneInto(),c=e._cloneInto,d=t._cloneInto;return{u1:(f,h)=>{a.setInt32(0,f,!1),i._cloneInto(s).update(n).digestInto(o),t._cloneInto(s).update(o).digestInto(o),h.set(o.subarray(0,h.length))},rounds:(f,h)=>{for(let u=1;u<f;u++){c.call(e,s).update(o).digestInto(o),d.call(t,s).update(o).digestInto(o);for(let p=0;p<h.length;p++)h[p]^=o[p]}},output:f=>(e.destroy(),t.destroy(),i.destroy(),s.destroy(),y(o),f)}}function xe(e,t,r,o){let{c:n,dkLen:a,DK:i,outputLen:s,eng:c}=ge(e,t,r,o);for(let d=1,f=0;f<a;d++,f+=s){let h=i.subarray(f,f+s);c.u1(d,h),c.rounds(n,h)}return c.output(i)}async function ye(e,t,r,o){let{c:n,dkLen:a,asyncTick:i,DK:s,outputLen:c,eng:d}=ge(e,t,r,o),f=()=>{d.output(s),y(s)};for(let h=1,u=0;u<a;h++,u+=c){let p=s.subarray(u,u+c);d.u1(h,p),await pe(n-1,i,()=>{d.rounds(2,p)},f)}return d.output(s)}var X=BigInt(4294967295),we=BigInt(32);function nt(e,t=!1){return t?{h:Number(e&X),l:Number(e>>we&X)}:{h:Number(e>>we&X)|0,l:Number(e&X)|0}}function ke(e,t=!1){let r=e.length,o=new Uint32Array(r),n=new Uint32Array(r);for(let a=0;a<r;a++){let{h:i,l:s}=nt(e[a],t);[o[a],n[a]]=[i,s]}return[o,n]}var at=e=>e/2**32|0,it=e=>e>>>0;function ve(e,t,r,o){let n=at(r),a=it(r);e.setUint32(t,o?a:n,o),e.setUint32(t+4,o?n:a,o)}var oe=(e,t,r)=>e>>>r,ne=(e,t,r)=>e<<32-r|t>>>r,_=(e,t,r)=>e>>>r|t<<32-r,z=(e,t,r)=>e<<32-r|t>>>r,D=(e,t,r)=>e<<64-r|t>>>r-32,q=(e,t,r)=>e>>>r-32|t<<64-r;function L(e,t,r,o){let n=(t>>>0)+(o>>>0);return{h:e+r+(n/2**32|0)|0,l:n|0}}var Le=(e,t,r)=>(e>>>0)+(t>>>0)+(r>>>0),Ae=(e,t,r,o)=>t+r+o+(e/2**32|0)|0,Ee=(e,t,r,o)=>(e>>>0)+(t>>>0)+(r>>>0)+(o>>>0),He=(e,t,r,o,n)=>t+r+o+n+(e/2**32|0)|0,Ue=(e,t,r,o,n)=>(e>>>0)+(t>>>0)+(r>>>0)+(o>>>0)+(n>>>0),Te=(e,t,r,o,n,a)=>t+r+o+n+a+(e/2**32|0)|0;function je(e,t,r){return e&t^~e&r}function Be(e,t,r){return e&t^e&r^t&r}var G=class{constructor(t,r,o,n){l(this,"blockLen");l(this,"outputLen");l(this,"canXOF",!1);l(this,"padOffset");l(this,"isLE");l(this,"buffer");l(this,"view");l(this,"finished",!1);l(this,"length",0);l(this,"pos",0);l(this,"destroyed",!1);this.blockLen=t,this.outputLen=r,this.padOffset=o,this.isLE=n,this.buffer=new Uint8Array(t),this.view=C(this.buffer)}update(t){I(this),T(t);let{view:r,buffer:o,blockLen:n}=this,a=t.length,i=!1;for(let s=0;s<a;){let c=Math.min(n-this.pos,a-s);if(c===n){let d=C(t);for(;n<=a-s;s+=n)this.process(d,s);i=!0;continue}o.set(s===0&&c===a?t:t.subarray(s,s+c),this.pos),this.pos+=c,s+=c,this.pos===n&&(this.process(r,0),this.pos=0,i=!0)}return this.length+=t.length,i&&this.roundClean(),this}digestInto(t){I(this),N(t,this),this.finished=!0;let{buffer:r,view:o,blockLen:n,isLE:a}=this,{pos:i}=this;r[i++]=128,r.fill(0,i),this.padOffset>n-i&&(this.process(o,0),r.fill(0)),ve(o,n-8,this.length*8,a),this.process(o,0),this.roundClean();let s=t===r?o:C(t),c=this.outputLen,d=c/4,f=this.get();if(c%4||d>f.length)throw new Error("invalid outputLen");for(let h=0;h<d;h++)s.setUint32(4*h,f[h],a)}digest(){let{buffer:t,outputLen:r}=this;this.digestInto(t);let o=t.slice(0,r);return this.destroy(),o}_cloneIntoMeta(t){let{buffer:r,length:o,finished:n,destroyed:a,pos:i}=this;return t.destroyed=a,t.finished=n,t.length=o,t.pos=i,i&&t.buffer.set(r),t}clone(){return this._cloneInto()}},Se=Uint32Array.from([1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225]);var _e=Uint32Array.from([1779033703,4089235720,3144134277,2227873595,1013904242,4271175723,2773480762,1595750129,1359893119,2917565137,2600822924,725511199,528734635,4215389547,1541459225,327033209]);var ct=Uint32Array.from([1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804,4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298]),j=new Uint32Array(64),ae=class extends G{constructor(r,o){super(64,r,8,!1);l(this,"A",0);l(this,"B",0);l(this,"C",0);l(this,"D",0);l(this,"E",0);l(this,"F",0);l(this,"G",0);l(this,"H",0);this.A=o[0]|0,this.B=o[1]|0,this.C=o[2]|0,this.D=o[3]|0,this.E=o[4]|0,this.F=o[5]|0,this.G=o[6]|0,this.H=o[7]|0}get(){let{A:r,B:o,C:n,D:a,E:i,F:s,G:c,H:d}=this;return[r,o,n,a,i,s,c,d]}set(r,o,n,a,i,s,c,d){this.A=r|0,this.B=o|0,this.C=n|0,this.D=a|0,this.E=i|0,this.F=s|0,this.G=c|0,this.H=d|0}_cloneInto(r){return(r||(r=new this.constructor)).set(...this.get()),this._cloneIntoMeta(r)}process(r,o){for(let u=0;u<16;u++,o+=4)j[u]=r.getUint32(o,!1);for(let u=16;u<64;u++){let p=j[u-15],m=j[u-2],g=k(p,7)^k(p,18)^p>>>3,x=k(m,17)^k(m,19)^m>>>10;j[u]=x+j[u-7]+g+j[u-16]|0}let{A:n,B:a,C:i,D:s,E:c,F:d,G:f,H:h}=this;for(let u=0;u<64;u++){let p=k(c,6)^k(c,11)^k(c,25),m=h+p+je(c,d,f)+ct[u]+j[u]|0,x=(k(n,2)^k(n,13)^k(n,22))+Be(n,a,i)|0;h=f,f=d,d=c,c=s+m|0,s=i,i=a,a=n,n=m+x|0}n=n+this.A|0,a=a+this.B|0,i=i+this.C|0,s=s+this.D|0,c=c+this.E|0,d=d+this.F|0,f=f+this.G|0,h=h+this.H|0,this.set(n,a,i,s,c,d,f,h)}roundClean(){y(j)}destroy(){this.destroyed=!0,this.set(0,0,0,0,0,0,0,0),y(this.buffer)}},ie=class extends ae{constructor(){super(32,Se)}};var ze=ke(["0x428a2f98d728ae22","0x7137449123ef65cd","0xb5c0fbcfec4d3b2f","0xe9b5dba58189dbbc","0x3956c25bf348b538","0x59f111f1b605d019","0x923f82a4af194f9b","0xab1c5ed5da6d8118","0xd807aa98a3030242","0x12835b0145706fbe","0x243185be4ee4b28c","0x550c7dc3d5ffb4e2","0x72be5d74f27b896f","0x80deb1fe3b1696b1","0x9bdc06a725c71235","0xc19bf174cf692694","0xe49b69c19ef14ad2","0xefbe4786384f25e3","0x0fc19dc68b8cd5b5","0x240ca1cc77ac9c65","0x2de92c6f592b0275","0x4a7484aa6ea6e483","0x5cb0a9dcbd41fbd4","0x76f988da831153b5","0x983e5152ee66dfab","0xa831c66d2db43210","0xb00327c898fb213f","0xbf597fc7beef0ee4","0xc6e00bf33da88fc2","0xd5a79147930aa725","0x06ca6351e003826f","0x142929670a0e6e70","0x27b70a8546d22ffc","0x2e1b21385c26c926","0x4d2c6dfc5ac42aed","0x53380d139d95b3df","0x650a73548baf63de","0x766a0abb3c77b2a8","0x81c2c92e47edaee6","0x92722c851482353b","0xa2bfe8a14cf10364","0xa81a664bbc423001","0xc24b8b70d0f89791","0xc76c51a30654be30","0xd192e819d6ef5218","0xd69906245565a910","0xf40e35855771202a","0x106aa07032bbd1b8","0x19a4c116b8d2d0c8","0x1e376c085141ab53","0x2748774cdf8eeb99","0x34b0bcb5e19b48a8","0x391c0cb3c5c95a63","0x4ed8aa4ae3418acb","0x5b9cca4f7763e373","0x682e6ff3d6b2b8a3","0x748f82ee5defb2fc","0x78a5636f43172f60","0x84c87814a1f0ab72","0x8cc702081a6439ec","0x90befffa23631e28","0xa4506cebde82bde9","0xbef9a3f7b2c67915","0xc67178f2e372532b","0xca273eceea26619c","0xd186b8c721c0c207","0xeada7dd6cde0eb1e","0xf57d4f7fee6ed178","0x06f067aa72176fba","0x0a637dc5a2c898a6","0x113f9804bef90dae","0x1b710b35131c471b","0x28db77f523047d84","0x32caab7b40c72493","0x3c9ebe0a15c9bebc","0x431d67c49c100d4c","0x4cc5d4becb3e42b6","0x597f299cfc657e2a","0x5fcb6fab3ad6faec","0x6c44198c4a475817"].map(e=>BigInt(e))),lt=ze[0],ut=ze[1],B=new Uint32Array(80),S=new Uint32Array(80),se=class extends G{constructor(r,o){super(128,r,16,!1);l(this,"Ah",0);l(this,"Al",0);l(this,"Bh",0);l(this,"Bl",0);l(this,"Ch",0);l(this,"Cl",0);l(this,"Dh",0);l(this,"Dl",0);l(this,"Eh",0);l(this,"El",0);l(this,"Fh",0);l(this,"Fl",0);l(this,"Gh",0);l(this,"Gl",0);l(this,"Hh",0);l(this,"Hl",0);this.Ah=o[0]|0,this.Al=o[1]|0,this.Bh=o[2]|0,this.Bl=o[3]|0,this.Ch=o[4]|0,this.Cl=o[5]|0,this.Dh=o[6]|0,this.Dl=o[7]|0,this.Eh=o[8]|0,this.El=o[9]|0,this.Fh=o[10]|0,this.Fl=o[11]|0,this.Gh=o[12]|0,this.Gl=o[13]|0,this.Hh=o[14]|0,this.Hl=o[15]|0}get(){let{Ah:r,Al:o,Bh:n,Bl:a,Ch:i,Cl:s,Dh:c,Dl:d,Eh:f,El:h,Fh:u,Fl:p,Gh:m,Gl:g,Hh:x,Hl:v}=this;return[r,o,n,a,i,s,c,d,f,h,u,p,m,g,x,v]}set(r,o,n,a,i,s,c,d,f,h,u,p,m,g,x,v){this.Ah=r|0,this.Al=o|0,this.Bh=n|0,this.Bl=a|0,this.Ch=i|0,this.Cl=s|0,this.Dh=c|0,this.Dl=d|0,this.Eh=f|0,this.El=h|0,this.Fh=u|0,this.Fl=p|0,this.Gh=m|0,this.Gl=g|0,this.Hh=x|0,this.Hl=v|0}_cloneInto(r){return(r||(r=new this.constructor)).set(...this.get()),this._cloneIntoMeta(r)}process(r,o){for(let b=0;b<16;b++,o+=4)B[b]=r.getUint32(o),S[b]=r.getUint32(o+=4);for(let b=16;b<80;b++){let H=B[b-15]|0,U=S[b-15]|0,P=_(H,U,1)^_(H,U,8)^oe(H,U,7),J=z(H,U,1)^z(H,U,8)^ne(H,U,7),A=B[b-2]|0,E=S[b-2]|0,M=_(A,E,19)^D(A,E,61)^oe(A,E,6),Y=z(A,E,19)^q(A,E,61)^ne(A,E,6),$=Ee(J,Y,S[b-7],S[b-16]),Q=He($,P,M,B[b-7],B[b-16]);B[b]=Q|0,S[b]=$|0}let{Ah:n,Al:a,Bh:i,Bl:s,Ch:c,Cl:d,Dh:f,Dl:h,Eh:u,El:p,Fh:m,Fl:g,Gh:x,Gl:v,Hh:O,Hl:F}=this;for(let b=0;b<80;b++){let H=_(u,p,14)^_(u,p,18)^D(u,p,41),U=z(u,p,14)^z(u,p,18)^q(u,p,41),P=u&m^~u&x,J=p&g^~p&v,A=Ue(F,U,J,ut[b],S[b]),E=Te(A,O,H,P,lt[b],B[b]),M=A|0,Y=_(n,a,28)^D(n,a,34)^D(n,a,39),$=z(n,a,28)^q(n,a,34)^q(n,a,39),Q=n&i^n&c^i&c,Ke=a&s^a&d^s&d;O=x|0,F=v|0,x=m|0,v=g|0,m=u|0,g=p|0,{h:u,l:p}=L(f|0,h|0,E|0,M|0),f=c|0,h=d|0,c=i|0,d=s|0,i=n|0,s=a|0;let de=Le(M,$,Ke);n=Ae(de,E,Y,Q),a=de|0}({h:n,l:a}=L(this.Ah|0,this.Al|0,n|0,a|0)),{h:i,l:s}=L(this.Bh|0,this.Bl|0,i|0,s|0),{h:c,l:d}=L(this.Ch|0,this.Cl|0,c|0,d|0),{h:f,l:h}=L(this.Dh|0,this.Dl|0,f|0,h|0),{h:u,l:p}=L(this.Eh|0,this.El|0,u|0,p|0),{h:m,l:g}=L(this.Fh|0,this.Fl|0,m|0,g|0),{h:x,l:v}=L(this.Gh|0,this.Gl|0,x|0,v|0),{h:O,l:F}=L(this.Hh|0,this.Hl|0,O|0,F|0),this.set(n,a,i,s,c,d,f,h,u,p,m,g,x,v,O,F)}roundClean(){y(B,S)}destroy(){this.destroyed=!0,y(this.buffer),this.set(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)}},ce=class extends se{constructor(){super(64,_e)}};var Ie=te(()=>new ie,re(1));var le=te(()=>new ce,re(3));var dt=e=>e[0]==="\u3042\u3044\u3053\u304F\u3057\u3093";function Ce(e){for(let t=0;t<e.length;t++){let r=e.charCodeAt(t);if(r>=55296&&r<=56319){if(t+1>=e.length)return!1;let o=e.charCodeAt(++t);if(o<56320||o>57343)return!1}else if(r>=56320&&r<=57343)return!1}return!0}function Oe(e){if(typeof e!="string")throw new TypeError("invalid mnemonic type: "+typeof e);if(!Ce(e))throw new TypeError("expected well-formed Unicode string");return e.normalize("NFKD")}function ue(e){let t=Oe(e),r=t.split(" ");if(![12,15,18,21,24].includes(r.length))throw new Error("Invalid mnemonic");return{nfkd:t,words:r}}function Fe(e){if(T(e),![16,20,24,28,32].includes(e.length))throw new RangeError("invalid entropy length")}function De(e,t=128){if(w(t),t%32!==0||t>256)throw new RangeError("Invalid entropy");return bt(be(t/8),e)}var qe=e=>{let t=8-e.length/4;return Ie(e)[0]>>t<<t};function Ge(e){if(!Array.isArray(e)||e.length!==2048||typeof e[0]!="string")throw new TypeError("Wordlist: expected array of 2048 strings");e.forEach(t=>{if(typeof t!="string")throw new TypeError("wordlist: non-string element: "+t);if(!Ce(t))throw new TypeError("wordlist: expected well-formed Unicode string")})}function ft(e,t){Ge(t);let r=new Uint8Array(e.length+1);r.set(e),r[e.length]=qe(e);let o=[],n=0,a=0;for(let i of r)n=n<<8|i,a+=8,a>=11&&(a-=11,o.push(t[n>>>a&2047]),n&=(1<<a)-1);return o}function ht(e,t){Ge(t);let r=e.length/3*4,o=new Uint8Array(r+1),n=0,a=0,i=0;for(let c of e){let d=t.indexOf(c);if(d===-1)throw new Error("Unknown word: "+c);for(n=n<<11|d,a+=11;a>=8;)a-=8,o[i++]=n>>>a&255;n&=(1<<a)-1}a>0&&(o[i]=n<<8-a);let s=o.subarray(0,r);if(o[r]!==qe(s))throw new Error("Invalid checksum");return Uint8Array.from(s)}function pt(e,t){let{words:r}=ue(e),o=ht(r,t);return Fe(o),o}function bt(e,t){return Fe(e),ft(e,t).join(dt(t)?"\u3000":" ")}function Me(e,t){try{pt(e,t)}catch{return!1}return!0}var $e=e=>{if(typeof e!="string")throw new TypeError("invalid passphrase type: "+typeof e);return Oe("mnemonic"+e)};function We(e,t=""){return ye(le,ue(e).nfkd,$e(t),{c:2048,dkLen:64})}function Re(e,t=""){return xe(le,ue(e).nfkd,$e(t),{c:2048,dkLen:64})}var Ne=Object.freeze(`abandon
ability
able
about
above
absent
absorb
abstract
absurd
abuse
access
accident
account
accuse
achieve
acid
acoustic
acquire
across
act
action
actor
actress
actual
adapt
add
addict
address
adjust
admit
adult
advance
advice
aerobic
affair
afford
afraid
again
age
agent
agree
ahead
aim
air
airport
aisle
alarm
album
alcohol
alert
alien
all
alley
allow
almost
alone
alpha
already
also
alter
always
amateur
amazing
among
amount
amused
analyst
anchor
ancient
anger
angle
angry
animal
ankle
announce
annual
another
answer
antenna
antique
anxiety
any
apart
apology
appear
apple
approve
april
arch
arctic
area
arena
argue
arm
armed
armor
army
around
arrange
arrest
arrive
arrow
art
artefact
artist
artwork
ask
aspect
assault
asset
assist
assume
asthma
athlete
atom
attack
attend
attitude
attract
auction
audit
august
aunt
author
auto
autumn
average
avocado
avoid
awake
aware
away
awesome
awful
awkward
axis
baby
bachelor
bacon
badge
bag
balance
balcony
ball
bamboo
banana
banner
bar
barely
bargain
barrel
base
basic
basket
battle
beach
bean
beauty
because
become
beef
before
begin
behave
behind
believe
below
belt
bench
benefit
best
betray
better
between
beyond
bicycle
bid
bike
bind
biology
bird
birth
bitter
black
blade
blame
blanket
blast
bleak
bless
blind
blood
blossom
blouse
blue
blur
blush
board
boat
body
boil
bomb
bone
bonus
book
boost
border
boring
borrow
boss
bottom
bounce
box
boy
bracket
brain
brand
brass
brave
bread
breeze
brick
bridge
brief
bright
bring
brisk
broccoli
broken
bronze
broom
brother
brown
brush
bubble
buddy
budget
buffalo
build
bulb
bulk
bullet
bundle
bunker
burden
burger
burst
bus
business
busy
butter
buyer
buzz
cabbage
cabin
cable
cactus
cage
cake
call
calm
camera
camp
can
canal
cancel
candy
cannon
canoe
canvas
canyon
capable
capital
captain
car
carbon
card
cargo
carpet
carry
cart
case
cash
casino
castle
casual
cat
catalog
catch
category
cattle
caught
cause
caution
cave
ceiling
celery
cement
census
century
cereal
certain
chair
chalk
champion
change
chaos
chapter
charge
chase
chat
cheap
check
cheese
chef
cherry
chest
chicken
chief
child
chimney
choice
choose
chronic
chuckle
chunk
churn
cigar
cinnamon
circle
citizen
city
civil
claim
clap
clarify
claw
clay
clean
clerk
clever
click
client
cliff
climb
clinic
clip
clock
clog
close
cloth
cloud
clown
club
clump
cluster
clutch
coach
coast
coconut
code
coffee
coil
coin
collect
color
column
combine
come
comfort
comic
common
company
concert
conduct
confirm
congress
connect
consider
control
convince
cook
cool
copper
copy
coral
core
corn
correct
cost
cotton
couch
country
couple
course
cousin
cover
coyote
crack
cradle
craft
cram
crane
crash
crater
crawl
crazy
cream
credit
creek
crew
cricket
crime
crisp
critic
crop
cross
crouch
crowd
crucial
cruel
cruise
crumble
crunch
crush
cry
crystal
cube
culture
cup
cupboard
curious
current
curtain
curve
cushion
custom
cute
cycle
dad
damage
damp
dance
danger
daring
dash
daughter
dawn
day
deal
debate
debris
decade
december
decide
decline
decorate
decrease
deer
defense
define
defy
degree
delay
deliver
demand
demise
denial
dentist
deny
depart
depend
deposit
depth
deputy
derive
describe
desert
design
desk
despair
destroy
detail
detect
develop
device
devote
diagram
dial
diamond
diary
dice
diesel
diet
differ
digital
dignity
dilemma
dinner
dinosaur
direct
dirt
disagree
discover
disease
dish
dismiss
disorder
display
distance
divert
divide
divorce
dizzy
doctor
document
dog
doll
dolphin
domain
donate
donkey
donor
door
dose
double
dove
draft
dragon
drama
drastic
draw
dream
dress
drift
drill
drink
drip
drive
drop
drum
dry
duck
dumb
dune
during
dust
dutch
duty
dwarf
dynamic
eager
eagle
early
earn
earth
easily
east
easy
echo
ecology
economy
edge
edit
educate
effort
egg
eight
either
elbow
elder
electric
elegant
element
elephant
elevator
elite
else
embark
embody
embrace
emerge
emotion
employ
empower
empty
enable
enact
end
endless
endorse
enemy
energy
enforce
engage
engine
enhance
enjoy
enlist
enough
enrich
enroll
ensure
enter
entire
entry
envelope
episode
equal
equip
era
erase
erode
erosion
error
erupt
escape
essay
essence
estate
eternal
ethics
evidence
evil
evoke
evolve
exact
example
excess
exchange
excite
exclude
excuse
execute
exercise
exhaust
exhibit
exile
exist
exit
exotic
expand
expect
expire
explain
expose
express
extend
extra
eye
eyebrow
fabric
face
faculty
fade
faint
faith
fall
false
fame
family
famous
fan
fancy
fantasy
farm
fashion
fat
fatal
father
fatigue
fault
favorite
feature
february
federal
fee
feed
feel
female
fence
festival
fetch
fever
few
fiber
fiction
field
figure
file
film
filter
final
find
fine
finger
finish
fire
firm
first
fiscal
fish
fit
fitness
fix
flag
flame
flash
flat
flavor
flee
flight
flip
float
flock
floor
flower
fluid
flush
fly
foam
focus
fog
foil
fold
follow
food
foot
force
forest
forget
fork
fortune
forum
forward
fossil
foster
found
fox
fragile
frame
frequent
fresh
friend
fringe
frog
front
frost
frown
frozen
fruit
fuel
fun
funny
furnace
fury
future
gadget
gain
galaxy
gallery
game
gap
garage
garbage
garden
garlic
garment
gas
gasp
gate
gather
gauge
gaze
general
genius
genre
gentle
genuine
gesture
ghost
giant
gift
giggle
ginger
giraffe
girl
give
glad
glance
glare
glass
glide
glimpse
globe
gloom
glory
glove
glow
glue
goat
goddess
gold
good
goose
gorilla
gospel
gossip
govern
gown
grab
grace
grain
grant
grape
grass
gravity
great
green
grid
grief
grit
grocery
group
grow
grunt
guard
guess
guide
guilt
guitar
gun
gym
habit
hair
half
hammer
hamster
hand
happy
harbor
hard
harsh
harvest
hat
have
hawk
hazard
head
health
heart
heavy
hedgehog
height
hello
helmet
help
hen
hero
hidden
high
hill
hint
hip
hire
history
hobby
hockey
hold
hole
holiday
hollow
home
honey
hood
hope
horn
horror
horse
hospital
host
hotel
hour
hover
hub
huge
human
humble
humor
hundred
hungry
hunt
hurdle
hurry
hurt
husband
hybrid
ice
icon
idea
identify
idle
ignore
ill
illegal
illness
image
imitate
immense
immune
impact
impose
improve
impulse
inch
include
income
increase
index
indicate
indoor
industry
infant
inflict
inform
inhale
inherit
initial
inject
injury
inmate
inner
innocent
input
inquiry
insane
insect
inside
inspire
install
intact
interest
into
invest
invite
involve
iron
island
isolate
issue
item
ivory
jacket
jaguar
jar
jazz
jealous
jeans
jelly
jewel
job
join
joke
journey
joy
judge
juice
jump
jungle
junior
junk
just
kangaroo
keen
keep
ketchup
key
kick
kid
kidney
kind
kingdom
kiss
kit
kitchen
kite
kitten
kiwi
knee
knife
knock
know
lab
label
labor
ladder
lady
lake
lamp
language
laptop
large
later
latin
laugh
laundry
lava
law
lawn
lawsuit
layer
lazy
leader
leaf
learn
leave
lecture
left
leg
legal
legend
leisure
lemon
lend
length
lens
leopard
lesson
letter
level
liar
liberty
library
license
life
lift
light
like
limb
limit
link
lion
liquid
list
little
live
lizard
load
loan
lobster
local
lock
logic
lonely
long
loop
lottery
loud
lounge
love
loyal
lucky
luggage
lumber
lunar
lunch
luxury
lyrics
machine
mad
magic
magnet
maid
mail
main
major
make
mammal
man
manage
mandate
mango
mansion
manual
maple
marble
march
margin
marine
market
marriage
mask
mass
master
match
material
math
matrix
matter
maximum
maze
meadow
mean
measure
meat
mechanic
medal
media
melody
melt
member
memory
mention
menu
mercy
merge
merit
merry
mesh
message
metal
method
middle
midnight
milk
million
mimic
mind
minimum
minor
minute
miracle
mirror
misery
miss
mistake
mix
mixed
mixture
mobile
model
modify
mom
moment
monitor
monkey
monster
month
moon
moral
more
morning
mosquito
mother
motion
motor
mountain
mouse
move
movie
much
muffin
mule
multiply
muscle
museum
mushroom
music
must
mutual
myself
mystery
myth
naive
name
napkin
narrow
nasty
nation
nature
near
neck
need
negative
neglect
neither
nephew
nerve
nest
net
network
neutral
never
news
next
nice
night
noble
noise
nominee
noodle
normal
north
nose
notable
note
nothing
notice
novel
now
nuclear
number
nurse
nut
oak
obey
object
oblige
obscure
observe
obtain
obvious
occur
ocean
october
odor
off
offer
office
often
oil
okay
old
olive
olympic
omit
once
one
onion
online
only
open
opera
opinion
oppose
option
orange
orbit
orchard
order
ordinary
organ
orient
original
orphan
ostrich
other
outdoor
outer
output
outside
oval
oven
over
own
owner
oxygen
oyster
ozone
pact
paddle
page
pair
palace
palm
panda
panel
panic
panther
paper
parade
parent
park
parrot
party
pass
patch
path
patient
patrol
pattern
pause
pave
payment
peace
peanut
pear
peasant
pelican
pen
penalty
pencil
people
pepper
perfect
permit
person
pet
phone
photo
phrase
physical
piano
picnic
picture
piece
pig
pigeon
pill
pilot
pink
pioneer
pipe
pistol
pitch
pizza
place
planet
plastic
plate
play
please
pledge
pluck
plug
plunge
poem
poet
point
polar
pole
police
pond
pony
pool
popular
portion
position
possible
post
potato
pottery
poverty
powder
power
practice
praise
predict
prefer
prepare
present
pretty
prevent
price
pride
primary
print
priority
prison
private
prize
problem
process
produce
profit
program
project
promote
proof
property
prosper
protect
proud
provide
public
pudding
pull
pulp
pulse
pumpkin
punch
pupil
puppy
purchase
purity
purpose
purse
push
put
puzzle
pyramid
quality
quantum
quarter
question
quick
quit
quiz
quote
rabbit
raccoon
race
rack
radar
radio
rail
rain
raise
rally
ramp
ranch
random
range
rapid
rare
rate
rather
raven
raw
razor
ready
real
reason
rebel
rebuild
recall
receive
recipe
record
recycle
reduce
reflect
reform
refuse
region
regret
regular
reject
relax
release
relief
rely
remain
remember
remind
remove
render
renew
rent
reopen
repair
repeat
replace
report
require
rescue
resemble
resist
resource
response
result
retire
retreat
return
reunion
reveal
review
reward
rhythm
rib
ribbon
rice
rich
ride
ridge
rifle
right
rigid
ring
riot
ripple
risk
ritual
rival
river
road
roast
robot
robust
rocket
romance
roof
rookie
room
rose
rotate
rough
round
route
royal
rubber
rude
rug
rule
run
runway
rural
sad
saddle
sadness
safe
sail
salad
salmon
salon
salt
salute
same
sample
sand
satisfy
satoshi
sauce
sausage
save
say
scale
scan
scare
scatter
scene
scheme
school
science
scissors
scorpion
scout
scrap
screen
script
scrub
sea
search
season
seat
second
secret
section
security
seed
seek
segment
select
sell
seminar
senior
sense
sentence
series
service
session
settle
setup
seven
shadow
shaft
shallow
share
shed
shell
sheriff
shield
shift
shine
ship
shiver
shock
shoe
shoot
shop
short
shoulder
shove
shrimp
shrug
shuffle
shy
sibling
sick
side
siege
sight
sign
silent
silk
silly
silver
similar
simple
since
sing
siren
sister
situate
six
size
skate
sketch
ski
skill
skin
skirt
skull
slab
slam
sleep
slender
slice
slide
slight
slim
slogan
slot
slow
slush
small
smart
smile
smoke
smooth
snack
snake
snap
sniff
snow
soap
soccer
social
sock
soda
soft
solar
soldier
solid
solution
solve
someone
song
soon
sorry
sort
soul
sound
soup
source
south
space
spare
spatial
spawn
speak
special
speed
spell
spend
sphere
spice
spider
spike
spin
spirit
split
spoil
sponsor
spoon
sport
spot
spray
spread
spring
spy
square
squeeze
squirrel
stable
stadium
staff
stage
stairs
stamp
stand
start
state
stay
steak
steel
stem
step
stereo
stick
still
sting
stock
stomach
stone
stool
story
stove
strategy
street
strike
strong
struggle
student
stuff
stumble
style
subject
submit
subway
success
such
sudden
suffer
sugar
suggest
suit
summer
sun
sunny
sunset
super
supply
supreme
sure
surface
surge
surprise
surround
survey
suspect
sustain
swallow
swamp
swap
swarm
swear
sweet
swift
swim
swing
switch
sword
symbol
symptom
syrup
system
table
tackle
tag
tail
talent
talk
tank
tape
target
task
taste
tattoo
taxi
teach
team
tell
ten
tenant
tennis
tent
term
test
text
thank
that
theme
then
theory
there
they
thing
this
thought
three
thrive
throw
thumb
thunder
ticket
tide
tiger
tilt
timber
time
tiny
tip
tired
tissue
title
toast
tobacco
today
toddler
toe
together
toilet
token
tomato
tomorrow
tone
tongue
tonight
tool
tooth
top
topic
topple
torch
tornado
tortoise
toss
total
tourist
toward
tower
town
toy
track
trade
traffic
tragic
train
transfer
trap
trash
travel
tray
treat
tree
trend
trial
tribe
trick
trigger
trim
trip
trophy
trouble
truck
true
truly
trumpet
trust
truth
try
tube
tuition
tumble
tuna
tunnel
turkey
turn
turtle
twelve
twenty
twice
twin
twist
two
type
typical
ugly
umbrella
unable
unaware
uncle
uncover
under
undo
unfair
unfold
unhappy
uniform
unique
unit
universe
unknown
unlock
until
unusual
unveil
update
upgrade
uphold
upon
upper
upset
urban
urge
usage
use
used
useful
useless
usual
utility
vacant
vacuum
vague
valid
valley
valve
van
vanish
vapor
various
vast
vault
vehicle
velvet
vendor
venture
venue
verb
verify
version
very
vessel
veteran
viable
vibrant
vicious
victory
video
view
village
vintage
violin
virtual
virus
visa
visit
visual
vital
vivid
vocal
voice
void
volcano
volume
vote
voyage
wage
wagon
wait
walk
wall
walnut
want
warfare
warm
warrior
wash
wasp
waste
water
wave
way
wealth
weapon
wear
weasel
weather
web
wedding
weekend
weird
welcome
west
wet
whale
what
wheat
wheel
when
where
whip
whisper
wide
width
wife
wild
will
win
window
wine
wing
wink
winner
winter
wire
wisdom
wise
wish
witness
wolf
woman
wonder
wood
wool
word
work
world
worry
worth
wrap
wreck
wrestle
wrist
write
wrong
yard
year
yellow
you
young
youth
zebra
zero
zone
zoo`.split(`
`));return Ve(mt);})();
/*! Bundled license information:

@scure/bip39/index.js:
  (*! scure-bip39 - MIT License (c) 2022 Patricio Palladino, Paul Miller (paulmillr.com) *)
*/
